num1 = int(input("Enter number 1 : "))
num2 = int(input("Enter number 2 : "))
if(num1>num2) : print(num1,"is greater than",num2)
elif(num2>num1) : print(num2,"is greater than",num1)
elif(num1 == num2) : print(num1,"is equal to",num2)